#!/usr/bin/env bash

alias  tic_labels_cat_csv='python3 ${TIC_LABELS_PYTHONPATH}/cat_csv.py'
alias  tic_labels_create_qa_labels='python3 ${TIC_LABELS_PYTHONPATH}/create_qa_labels.py'
alias  tic_labels_create_mask='python3 ${TIC_LABELS_PYTHONPATH}/create_mask.py'
alias  tic_labels_create_sphere='python2 ${TIC_LABELS_PYTHONPATH}/create_sphere.py'
alias  tic_labels_extract='python2 ${TIC_LABELS_PYTHONPATH}/extract.py'
alias  tic_labels_keep='python2 ${TIC_LABELS_PYTHONPATH}/keep.py'
alias  tic_labels_lcc='python2 ${TIC_LABELS_PYTHONPATH}/label_connected_components.py'
alias  tic_labels_list='python2 ${TIC_LABELS_PYTHONPATH}/list.py'
alias  tic_labels_measure='python2 ${TIC_LABELS_PYTHONPATH}/measure.py'
alias  tic_labels_remove='python2 ${TIC_LABELS_PYTHONPATH}/remove.py'
alias  tic_labels_properties='python2 ${TIC_LABELS_PYTHONPATH}/properties.py'
alias  tic_labels_set='python2 ${TIC_LABELS_PYTHONPATH}/set.py'
alias  tic_labels_sort='python2 ${TIC_LABELS_PYTHONPATH}/sort.py'
alias  tic_labels_where='python2 ${TIC_LABELS_PYTHONPATH}/where.py'
